networks:
  nginx:
    internal: false
services:
  nginx:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'nginx'
    cap_drop:
      - 'ALL'
    healthcheck:
      interval: '10s'
      retries: 3
      start_period: '30s'
      test:
        - 'CMD-SHELL'
        - 'curl -fsSL http://localhost:61100/nginx_ping | grep -q pong || exit 1'
      timeout: '5s'
    logging:
      driver: 'json-file'
      options:
        max-file: 3
        max-size: '10m'
    networks:
      - 'nginx'
    read_only: true
    restart: 'unless-stopped'
    security_opt:
      - 'no-new-privileges:true'
    stop_grace_period: '60s'
    sysctls:
      - 'net.core.somaxconn=65535'
      - 'net.ipv4.ip_local_port_range=1024 65535'
      - 'net.ipv4.tcp_fin_timeout=15'
      - 'net.ipv4.tcp_tw_reuse=1'
    ulimits:
      nofile:
        hard: 1048576
        soft: 1048576
    user: 'nginx:nginx'
    volumes:
      - target: '/tmp'
        tmpfs:
          mode: 01777
        type: 'tmpfs'
      - target: '/run'
        tmpfs:
          mode: 01777
        type: 'tmpfs'
