networks:
  devcontainer:
    internal: false
services:
  devcontainer:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    command: 'sleep infinity'
    environment:
      APP_ENV: 'local'
      APP_VERSION: 'dev'
      NODE_ENV: 'development'
      NPM_CONFIG_CACHE: '/home/node/.npm'
    init: true
    networks:
      - 'devcontainer'
    ports:
      - host_ip: '127.0.0.1'
        published: 61101
        protocol: 'tcp'
        target: 61101
    user: 'node:node'
    volumes:
      - './:/workspaces'
      - 'npm-cache:/home/node/.npm'
  nginx:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'nginx'
    networks:
      - 'devcontainer'
    ports:
      - host_ip: '127.0.0.1'
        published: 61100
        protocol: 'tcp'
        target: 61100
volumes:
  npm-cache:
    external: true
    name: 'tomaschochola-npm-cache'
