worker_processes auto;
worker_cpu_affinity auto;

pid /tmp/nginx.pid;

error_log /proc/self/fd/2 crit;

worker_rlimit_nofile 1048576;

pcre_jit on;

events {
  worker_connections 16384;
  multi_accept on;
}

http {
  proxy_temp_path /tmp/proxy_temp;
  client_body_temp_path /tmp/client_temp;
  fastcgi_temp_path /tmp/fastcgi_temp;
  uwsgi_temp_path /tmp/uwsgi_temp;
  scgi_temp_path /tmp/scgi_temp;

  include /etc/nginx/mime.types;

  server_tokens off;

  charset utf-8;

  tcp_nodelay on;
  tcp_nopush on;
  sendfile on;

  default_type application/octet-stream;

  index index.html /index.html;

  client_max_body_size 16k;
  client_body_buffer_size 16k;
  client_body_in_single_buffer on;

  open_file_cache max=100000 inactive=60s;
  open_file_cache_valid 60s;
  open_file_cache_min_uses 1;
  open_file_cache_errors on;

  access_log off;
  log_not_found off;

  reset_timedout_connection on;

  send_timeout 5s;
  client_body_timeout 5s;
  client_header_timeout 5s;
  resolver_timeout 5s;

  keepalive_timeout 60s;
  keepalive_requests 1000;

  fastcgi_keep_conn on;
  fastcgi_socket_keepalive on;

  server {
    listen 8080 default_server backlog=65535 reuseport;

    server_name "";

    root /var/www/html;

    include /etc/nginx/snippets/add_header_security_headers.conf;
    expires epoch;
    add_header Cache-Control "public, no-cache, max-age=0";

    location / {
      limit_except GET {
        deny all;
      }

      try_files $uri /index.html;
    }

    location = /nginx_ping {
      add_header Content-Type "text/plain; charset=utf-8";

      return 200 'pong';
    }

    location ^~ /social/ {
      limit_except GET {
        deny all;
      }

      include /etc/nginx/snippets/add_header_public_asset_headers.conf;
      expires max;
      add_header Cache-Control "public, max-age=31536000, immutable";

      try_files $uri =404;
    }

    location ^~ /icons/ {
      limit_except GET {
        deny all;
      }

      include /etc/nginx/snippets/add_header_public_asset_headers.conf;
      expires max;
      add_header Cache-Control "public, max-age=31536000, immutable";

      try_files $uri =404;
    }

    location = /apple-touch-icon.png {
      limit_except GET {
        deny all;
      }

      include /etc/nginx/snippets/add_header_public_asset_headers.conf;
      expires max;
      add_header Cache-Control "public, max-age=31536000, immutable";

      try_files $uri =404;
    }

    location = /favicon.ico {
      limit_except GET {
        deny all;
      }

      include /etc/nginx/snippets/add_header_public_asset_headers.conf;
      expires max;
      add_header Cache-Control "public, max-age=31536000, immutable";

      try_files $uri =404;
    }

    location = /favicon.svg {
      limit_except GET {
        deny all;
      }

      include /etc/nginx/snippets/add_header_public_asset_headers.conf;
      expires max;
      add_header Cache-Control "public, max-age=31536000, immutable";

      try_files $uri =404;
    }

    location = /favicon-96x96.png {
      limit_except GET {
        deny all;
      }

      include /etc/nginx/snippets/add_header_public_asset_headers.conf;
      expires max;
      add_header Cache-Control "public, max-age=31536000, immutable";

      try_files $uri =404;
    }

    location ~* \.html$ {
      limit_except GET {
        deny all;
      }

      include /etc/nginx/snippets/add_header_security_headers.conf;
      expires epoch;
      add_header Cache-Control "private, no-store, max-age=0";
    }

    location ^~ /immutable. {
      limit_except GET {
        deny all;
      }

      include /etc/nginx/snippets/add_header_security_headers.conf;
      expires max;
      add_header Cache-Control "public, max-age=31536000, immutable";
    }
  }
}
